version: 2
jobs:
  references:
    ## Workspace
    workspace: &workspace
                 ~/workspace
    attach_debug_workspace: &attach_debug_workspace
      attach_workspace:
        at: *workspace
    persist_debug_workspace: &persist_debug_workspace
      persist_to_workspace:
        root: *workspace
        paths:
          - build/libs
          - build/test-results/

  build:
    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: gradle build

      - *persist_debug_workspace
      - store_artifacts:
          path: build/libs/
          destination: /libs/

  test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: gradle test

      - *persist_debug_workspace
      - store_artifacts:
          path: build/reports/
          destination: /reports/
      - store_test_results:
          path: build/test-results/
          destination: /test-results/

  jacoco_test_reports:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - *attach_debug_workspace
      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: gradle jacocoTestReport

      - store_artifacts:
          path: build/reports/
          destination: /reports/

workflows:
  version: 2
  workflows:
    jobs:
      - build
      - test
      - jacoco_test_reports:
          requires:
            - build
            - test