version: 2
references:
  ## Workspace
  workspace: &workspace
    ~/workspace
  attach_debug_workspace: &attach_debug_workspace
    attach_workspace:
      at: *workspace
  persist_debug_workspace: &persist_debug_workspace
    persist_to_workspace:
      root: *workspace
      paths:
        - build/libs
        - build/test-results/

  ## Docker images
  config: &android_config
    working_directory: *workspace
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
      TERM: dumb
      _JAVA_OPTIONS: "-Xmx1800m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx1800m"'

jobs:
  assemble:
    <<: *android_config
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradlew
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: ./gradlew assemble

      - *persist_debug_workspace
      - store_artifacts:
          path: build/libs/
          destination: /libs/

  test:
    <<: *android_config
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradlew
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: ./gradlew -PciBuild=true test

      - *persist_debug_workspace
      - store_artifacts:
          path: build/reports/
          destination: /reports/
      - store_test_results:
          path: build/test-results/
          destination: /test-results/

  jacoco_test_reports:
    <<: *android_config
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - *attach_debug_workspace
      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradlew
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: ./gradlew -PciBuild=true jacocoTestReport

      - store_artifacts:
          path: build/reports/
          destination: /reports/

workflows:
  version: 2
  workflows:
    jobs:
      - assemble
      - test
      - jacoco_test_reports:
          requires:
            - test